### ISSUE TITLE
404 when trying to delete product from the dropdown

### ISSUE THREAD

**Issue by benface** [craftcms/digital-products#24]
Deleting a product using this "Delete" button works:

<img width="335" alt="screen shot 2018-10-19 at 4 22 37 pm" src="https://user-images.githubusercontent.com/1059139/47241875-379a3c00-d3bb-11e8-8869-cfaf974ab1f4.png">

But doing it using the dropdown above it doesn't:

<img width="309" alt="screen shot 2018-10-19 at 4 21 52 pm" src="https://user-images.githubusercontent.com/1059139/47241894-4254d100-d3bb-11e8-9dd5-5d576b022a41.png">

<img width="836" alt="screen shot 2018-10-19 at 4 23 12 pm" src="https://user-images.githubusercontent.com/1059139/47241910-4b45a280-d3bb-11e8-9977-b4a2a16248e0.png">

**Comment by andris-sevcenko** [comment]
Fixed via 21d5e9c
