### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by benface** [craftcms/digital-products#25]
<img width="834" alt="screen shot 2018-10-19 at 4 31 43 pm" src="https://user-images.githubusercontent.com/1059139/47242366-87c5ce00-d3bc-11e8-87e3-4281995009a0.png">

**Comment by andris-sevcenko** [comment]
Fixed via 21a0962

**Comment by andris-sevcenko** [comment]
Fixed via 21a0962
