### ISSUE TITLE
Undefined Class Constant 'EVENT_BEFORE_PROCESS_PAYMENT'

### ISSUE THREAD

**Issue by j2is** [craftcms/digital-products#31]
I get this error when attempting to install the plugin, I assume this is because my Craft Commerce is in trial mode and I have not yet licensed it?

**Comment by andris-sevcenko** [comment]
There should be a stack trace in your logs somewhere. Are you using any other plugins?

**Comment by j2is** [comment]
Sorry was just a PEBCAK, I updated Craft and Commerce and was able to install
