### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by peirix** [craftcms/digital-products#32]
Somehow the first try of installing the plugin failed, but managed to do some SQL, because on the next try I got this error:

```
[-][1][-][error][craft\db\MigrationManager::migrateUp] Failed to apply Install (time: 0.035s). Output:
    > create table {{%digitalproducts_licenses}} ...Exception: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'craft_digitalproducts_licenses' already exists
The SQL being executed was: CREATE TABLE `craft_digitalproducts_licenses` (
	`id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`productId` int(11) NOT NULL,
	`orderId` int(11) NULL DEFAULT NULL,
	`licenseKey` varchar(255) NOT NULL,
	`ownerName` varchar(255),
	`ownerEmail` varchar(255) NOT NULL,
	`userId` int(11) NULL DEFAULT NULL,
	`dateCreated` datetime(0) NOT NULL,
	`dateUpdated` datetime(0) NOT NULL,
	`uid` char(36) NOT NULL DEFAULT '0'
) ENGINE=InnoDb DEFAULT CHARSET=utf8
```

**Comment by angrybrad** [comment]
> Somehow the first try of installing the plugin failed

What was the error on the first fail?

**Comment by peirix** [comment]
I didn't check, and I deleted the `log` file :(

But it might be because I had Craft Commerce Lite installed, and not the Pro version?

**Comment by angrybrad** [comment]
Weird... I'm not able to reproduce that, but if you run into it again, feel free to comment back here and we'll reopen.

**Comment by peirix** [comment]
Sure. Will do. Just thought it might be a good idea to have `DROP TABLE IF EXISTS` in there. (:
