### ISSUE TITLE
Showing 0 results with Element API

### ISSUE THREAD

**Issue by peirix** [craftcms/digital-products#37]
When trying to fetch digital products using Element API, I get 0 results. Using the following code:

```
use craft\digitalproducts\elements\Product;

return [
  'endpoints' => [
    'songs.json' => function() {
      return [
        'elementType' => Product::class,
        'transformer' => function(Product $entry) {
          return [
            'title' => $entry->title
          ];
        },
      ];
    },
  ]
];
```

Versions:
Craft: 3.1.25
Commerce: 2.1.5.2
Digital Products: 2.2.0
Element API: 2.5.4

**Comment by andris-sevcenko** [comment]
I'm not able to reproduce this locally. Can you send over your DB dump, composer.lock, and composer.json files over to support@cratcms.com referencing this issue?

**Comment by peirix** [comment]
Turned out to be a unrelated issue with FeedMe.
