### ISSUE TITLE
Product Type Permissions Broken

### ISSUE THREAD

**Issue by devkokov** [craftcms/digital-products#42]
Permissions specific to product types are saved as:

`digitalProducts-manageProductType:productTypeId`

but checked as:

`$this->requirePermission('digitalProducts-manageProducts:' . $product->typeId);`

This means that currently only super admins can create/edit products.

**Comment by andris-sevcenko** [comment]
Yikes, thank you!

**Comment by devkokov** [comment]
@andris-sevcenko thanks for the quick fix!

The permissions work fine now when trying to edit a product directly e.g. /admin/digital-products/products/productType/ID , but the main products listing page doesn't show any products or product types, and the button to add new products is missing from top right.

I've had a look at the DigitalProductsProductIndex.js file but couldn't decipher what's wrong.

**Comment by andris-sevcenko** [comment]
Ugh, of course. Because Digital Products hasn't _really_ been converted to using UIDs instead of IDs in the source keys. Hang on.
