### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/digital-products#44]
With Craft 3.3.6 and Digital Products 2.3.0, deprecation warnings are generated with the following messages:

_(templates/producttypes/index.html)..._
- {% includeJs %} is now deprecated. Use {% js %} instead. 

_(templates/products/\_edit.html)..._
- getCsrfInput() has been deprecated. Use csrfInput() instead.

**Comment by nfourtythree** [comment]
Thanks for the heads up @rob-baker-ar 

Will get a release pushed for this
