### ISSUE TITLE
Can you query digital product data using Graphql

### ISSUE THREAD

**Issue by satcreative** [craftcms/digital-products#46]
I'm hoping to query digital product data via Graphql, however the digital products data doesn't appear in the Graphql/Schemas options. Is this not possible like it is with typical commerce products?

**Comment by nfourtythree** [comment]
Hi

We have just released `2.4.0` which includes support for this. The readme has been updated with relevant GraphQL documentation.

Thanks!

**Comment by satcreative** [comment]
Oh, that's great. Much appreciated!
