### ISSUE TITLE
Add product button disappeared

### ISSUE THREAD

**Issue by kevadamson** [craftcms/digital-products#49]
### Description

Add product button seems to have gone missing on /admin/digital-products/products

Also, if I try and "Save as a new product" I get the following error:

`Integrity constraint violation – yii\db\IntegrityException
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'foo' for key 'digitalproducts_products_sku_unq_idx'
The SQL being executed was: INSERT INTO `digitalproducts_products` (`id`, `postDate`, `expiryDate`, `typeId`, `promotable`, `taxCategoryId`, `price`, `sku`, `dateCreated`, `dateUpdated`, `uid`) VALUES (1011, '2020-08-01 14:27:00', NULL, 1, 0, 1, '10', 'foo', '2020-08-19 17:19:32', '2020-08-19 17:19:32', 'a133ada6-c5ee-42f2-91e7-7e07d505b834')
Error Info: Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry 'foo' for key 'digitalproducts_products_sku_unq_idx'
)
↵
Caused by: PDOException
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'foo' for key 'digitalproducts_products_sku_unq_idx'
in /var/www/foo/vendor/yiisoft/yii2/db/Command.php at line 1293`

### Steps to reproduce

1. /admin/digital-products/products

### Additional info

- Craft version: Craft Pro 3.5.5
- PHP version: 7.1.33
- Database driver & version: MySQL 5.6.47
- Plugins & versions:

Cloner 1.1.2
Conditional Fields 0.0.6
Control Panel Body Classes 2.2.1
Control Panel CSS 2.2.1
CP Field Inspect 1.2.1
Craft Commerce 3.2.2.1
Dashboard Begone 1.0.1
Digital Products 2.4.0
Expanded Singles 1.1.3
Express Forms 1.0.6
Field and Tab Permissions 1.4.0
Field Manager 2.1.8
Internal Assets 2.3.1
Redactor 2.7.1
Redactor Anchors 1.1.0
Redactor Custom Styles 3.0.4
Redactor nofollow link plugin 1.0.1
Single Cat 1.2.1
Super Table 2.6.1

**Comment by kevadamson** [comment]
Tried deleting product to add another, and the button has gone completely  - so can't add any products now.

I've tried disabling plugins one by one, still not showing.

I've tried a fresh install of the plugin.

**Comment by lukeholder** [comment]
Thanks for reporting that! I’ve just fixed it for the next release.

To get the fix early, change your `craftcms/commerce` requirement in composer.json to:

```json
"require": {
  "craftcms/digital-products": "dev-develop#a42cd08363a0eeea0b2eb518078960a1b0099096 as 2.4.0",
  "...": "..."
}
```

Then run `composer update`.
