### ISSUE TITLE
Search results not showing for keyword in title

### ISSUE THREAD

**Issue by kevadamson** [craftcms/digital-products#50]
### Description

Not sure if this is just me, but when I have a product say with the word "red" in its title, then use a keyword search for "red" nothing shows, while other fields set to show in search results are working fine.

### Steps to reproduce

`{% paginate craft.digitalProducts.products.search(query).orderBy('score').limit(4) as products %}`

` <input type="search" name="q" class="type_text" placeholder="Keyword" {% if query|length %}value="{{ query }}"{% endif %} />`

### Additional info

- Craft version: Craft Pro 3.5.5
- PHP version: 7.1.33
- Database driver & version: MySQL 5.6.47
- Plugins & versions:

Digital Products 2.4.1
Craft Commerce 3.2.3

**Comment by angrybrad** [comment]
This is working for me:

<img width="514" alt="CleanShot 2020-08-24 at 07 35 54@2x" src="https://user-images.githubusercontent.com/61869/91057738-77946080-e5dc-11ea-91bc-f3024ac9bd41.png">

My guess is if you run `./craft resave/products` from your project's root to rebuild your search index, your example will start working.
