### ISSUE TITLE
Hard deleting products does nothing

### ISSUE THREAD

**Issue by peirix** [craftcms/digital-products#56]
### Description
Trying to hard delete products after deleting them does nothing. It sends off a query to `admin/actions/element-indexes/perform-action&v=1605644023795` with an `elementAction`: `craft\digitalproducts\elements\actions\DeleteProduct` along with an array of the items I selected. The return value says `success: true`, but the products are still there.

### Steps to reproduce

1. Create a new product
2. Delete the product
3. Go to trash bin
4. Hard delete product

### Additional info

- Craft version: 3.5.15.1
- PHP version: 7.4.2
- Database driver & version: mysql 5.7.26
- Plugins & versions: Digital products 2.4.1 and Commerce 3.2.11

**Comment by nfourtythree** [comment]
Hi @peirix 

Thank you for bringing this to our attention, we have pushed a fix to rectify the issue which will be included in the next release.

Thanks!
