### ISSUE TITLE
Getting UI-elements from Craft 3.5 into the field layout

### ISSUE THREAD

**Issue by peirix** [craftcms/digital-products#60]
### Description

It would be nice to have the same UI elements in the field layout designer that was implementet for entries with Craft 3.5. Both the ability to set field width and adding UI elements.

**Comment by Coysh** [comment]
+1 for this. Still using Craft Field Instructions for this, which has been marked as abandoned

**Comment by lukeholder** [comment]
This is fixed for the next release.
