### ISSUE TITLE
Internal error if SKU not unique?

### ISSUE THREAD

**Issue by kevadamson** [craftcms/digital-products#61]
### Description

A less fatal error handling rather than an internal error I think is needed

### Steps to reproduce

1. Create product
2. Add SKU that already exists

### Additional info

- Craft version: Craft Pro 3.5.16
- PHP version: 7.1.21
- Database driver & version: MySQL 5.5.62
- Plugins & versions: 2.4.1

**Comment by nfourtythree** [comment]
Hi @kevadamson 

Thank you for bringing this to our attention, we have pushed a fix for this issue. The fix will be included in the next release.

Thanks!
