### ISSUE TITLE
Unable to save Licenses

### ISSUE THREAD

**Issue by Coysh** [craftcms/digital-products#63]
### Description
When updating a license, modifying any of the following fields does not update:

- Product
- Owner
- Owner name

Though updating the following fields does work:

- Owner email
- Enabled?

This bug appears in the front end, but also attempting to programatically edit fields fails:
```
$license = Craft::$app->getElements()->getElementById($licenseID, License::class);

if (!$license) {
	throw new Exception('No license with the ID “{id}”', ['id' => $licenseID]);
}
		
$license->productId = $newProductId;

$success = Craft::$app->getElements()->saveElement($license);
if (!$success) {
	Craft::error('Couldn’t save the license ', __METHOD__);
	return false;
} else {
	Craft::info('Saved the license', __METHOD__);
}
return $this->redirectToPostedUrl();
```

The log shows "Saved the license", but the license in `digitalproducts_license` has not been updated.
However the element for the licenese in `elements` has been update with a new `dateUpdated` date.

- Craft version: 3.6.12.1
- PHP version: 7.4.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Digital Products 2.4.3.1

**Comment by lukeholder** [comment]
Those properties are immutable after first save of the license

https://github.com/craftcms/digital-products/blob/22fc70b6ce47345f257e81f6d18a416fb5f4277e/src/elements/License.php#L395-L399

You should create a new license and remove the old one if you want to create a new license.
