### ISSUE TITLE
Garbage collection fails with integrity constraint violation

### ISSUE THREAD

**Issue by rob-baker-ar** [craftcms/digital-products#75]
### Description

Running Craft's garbage collection (i.e. `php craft gc`) a database exception is thrown as follows:

```
Error: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails ([database].`digitalproducts_licenses`, CONSTRAINT `digitalproducts_licenses_productId_fk` FOREIGN KEY (`productId`) REFERENCES `digitalproducts_products` (`id`))
The SQL being executed was: DELETE FROM `elements` WHERE NOT (`dateDeleted` IS NULL)
```

### Steps to reproduce

1. Have a Craft & Commerce install with some  digital product licenses present
2. Run `php craft gc`

### Additional info

This was encountered immediately prior to upgrading Craft & Commerce to v4 on the advice of @angrybrad via support, attempting to work around another non-relevant issue.

- Craft version: 3.7.51
- PHP version: 8.1.2
- Database driver & version: MySQL 5.5.5
- Relevant Plugins & versions:
  - Digital Download `2.1.9`
  - Digital Products `2.4.3.2`
  - Craft Commerce `3.4.16`

**Comment by pdaleramirez** [comment]
@rob-baker-ar This is a known issue. We are thinking of ways on how to deal with this bug.

**Comment by lukeholder** [comment]
This has been fixed for the next release. The migration will restore the soft deleted digital products but set them to disabled. All licenses need to be deleted before a digital product can be soft deleted.
