### ISSUE TITLE
Cannot edit or delete a Digital Product

### ISSUE THREAD

**Issue by joneslafuente** [craftcms/digital-products#79]
### Description
I have several products added and all work fine but I cannot change the status, edit or delete them

### Steps to reproduce

1. Add new product
2. Click on the dropdown that should allow you to view, edit or delete. It is greyed out for edit and delete as is the set status dropdown entirely.

### Additional info

- Craft version: 4.3.5
- PHP version: 8.0.26
- Database driver & version: MySQL 10.3.37
- Plugins & versions: Commerce 4.2.4, Digital Products 3.1.0, Embedded Assets 3.1.0, Freeform 4.0.9, Neo 3.5.13, Redactor 3.0.2

**Comment by joneslafuente** [comment]
OK still no response on this, I have done further test and this plugin does not play at all well with Craft 4. Tried on several installations now and all the same result. Cannot edit, delete or change the status. A complete waste with Craft 4.

Craft 3 on the other hand works well. Maybe when it is updated to work with Craft 4 somebody would like to update this, or a workaround? Until then if you need to have digital products on your commerce site, stick with version 3.

**Comment by pdaleramirez** [comment]
I've tested this and it is a bug on the CMS version > 4.3.1.

**Comment by lukeholder** [comment]
This was fixed in 3.2.0, just released.
