### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by berrytimmermans** [craftcms/digital-products#95]
### Description

Jump into Craft’s included GraphiQL IDE from the control panel results in the following deprecation warning'.

Message: TypeManager::prepareFieldDefinitions() has been deprecated. Use craft\services\Gql::prepareFieldDefinition() instead.
Origin: /var/www/html/vendor/craftcms/digital-products/src/gql/interfaces/elements/Product.php:91

### Additional info

- Craft version: 4.5.11.1
- PHP version: 8.1.26
- Database driver & version: MariaDB 10.5.23
- Plugins & versions: Craft Commerce 4.3.2, Digital Products 3.2.3

**Comment by lukeholder** [comment]
Thanks for reporting this. It is fixed for the next release. d9597c7eff201df59fe5b167a66d705103904095
