### ISSUE TITLE
Unable to query Digital Products with GraphQL: `Cannot query field "digitalProduct" on type "Query"`

### ISSUE THREAD

**Issue by tommysvr** [craftcms/digital-products#96]
### Description
Unable to query Digital Products with GraphQL.

Using the [example in the docs](https://github.com/craftcms/digital-products?tab=readme-ov-file#graphql):

```
query {
    digitalProducts(type: "eBooks", limit: 2) {
        title,
        sku,
        price
    }
}
```

Returns:

```
{
  "errors": [
    {
      "message": "Cannot query field \"digitalProducts\" on type \"Query\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 5
        }
      ]
    }
  ]
}
```

### Additional info
`digitalProducts` and `digitalProduct` are not available in the explorer.

- Craft version: 4.8 (also tested on 3.9.10)
- Plugins & versions: Commerce 3.4.23  / Digital Products 2.4.3.2

**Comment by lukeholder** [comment]
This should now be fixed in 4.0.2 thanks!
